# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59cdc07d18ee2d401b73332dbdf3950948f14f9e6a4a4e5224691829ea5c5e43c2cc05dfe2cdf141d201026700c0140bc38cfbe271ece1abefcda95ac9ebafbe

test:
  secret_key_base: 4e8fa2448c24d2cd4e3ce2bbf40c21d598a888982753fd86513df014338ed639ca3d2d5198b465077f6e9f8663df2eeb8f456a8a3257d1869506c91bd5c73e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
